AlmostEmptyWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HelloWorld_MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AlmostEmptyWebsite/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace HelloWorld_MVC.Controllers
{
    public class PagesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Pictures()
        {
            return View();
        }
    }
}

AlmostEmptyWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

This is a home page with a very important first impression to make on new visitors.

AlmostEmptyWebsite/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <h2>Hello World!</h2>

        <nav>
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Main Page</a>
                </li>
                <li>
                    <a asp-controller="Pages" asp-action="Index">Pages</a>
                </li>
            </ul>
        </nav>

    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        <p>This is a footer. </p>&copy; @DateTime.Now.Year
    </footer>
</body>

</html>